import path from 'node:path';

const source = path.join(
	import.meta.dir,
	'../node_modules/dialkit/dist/styles.css',
);
const destination = path.join(
	import.meta.dir,
	'../src/dialkit-styles.generated.ts',
);
const css = await Bun.file(source).text();

await Bun.write(
	destination,
	`// Generated by scripts/embed-dialkit-styles.ts. Do not edit.\nexport const dialKitStyles = ${JSON.stringify(css)};\n`,
);

const formatter = Bun.spawn(['bunx', 'oxfmt', destination], {
	stdout: 'inherit',
	stderr: 'inherit',
});
if ((await formatter.exited) !== 0) {
	throw new Error('Could not format the embedded DialKit stylesheet');
}
